development:
  host: localhost
  adapter: postgresql
  database: fartuhabr
  username: admin
  password: KVPIgFN1
test:
  host: localhost
  adapter: postgresql
  database: fartuhabr
  username: admin
  password: KVPIgFN1

production:
  host: localhost
  adapter: postgresql
  database: fartuhabr
  username: admin
  password: KVPIgFN1
